list=[]
print("Empty list of integers created :  ",list)
list.insert(0,5)
list.insert(1,7)
list.insert(0,9)
print("After addition  tree integers :  ",list)
list.remove(9)
list.append(11)
list.append(4)
print(list)
list.sort()
print("List sorted :  ",list)
list.pop()
print("After pop operation :  ",list)
list.reverse()
print("List reversed :  ",list)
